//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeX.DesktopTool.Print.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ZDesigner GK420T")]
        public string LabelPrinterName {
            get {
                return ((string)(this["LabelPrinterName"]));
            }
            set {
                this["LabelPrinterName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Linear")]
        public string BarcodeType {
            get {
                return ((string)(this["BarcodeType"]));
            }
            set {
                this["BarcodeType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ItemCode")]
        public string BarcodeValue {
            get {
                return ((string)(this["BarcodeValue"]));
            }
            set {
                this["BarcodeValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Source\\Development\\WinApp\\BarindoPrint\\bin\\Debug\\Data")]
        public string RemoteDataPath {
            get {
                return ((string)(this["RemoteDataPath"]));
            }
            set {
                this["RemoteDataPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Local")]
        public string DataMode {
            get {
                return ((string)(this["DataMode"]));
            }
            set {
                this["DataMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string PrintLabelNo {
            get {
                return ((string)(this["PrintLabelNo"]));
            }
            set {
                this["PrintLabelNo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int AutoSaveLogFile {
            get {
                return ((int)(this["AutoSaveLogFile"]));
            }
            set {
                this["AutoSaveLogFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int CheckPrinterStatusInterval {
            get {
                return ((int)(this["CheckPrinterStatusInterval"]));
            }
            set {
                this["CheckPrinterStatusInterval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ClearLogFileWhenExit {
            get {
                return ((bool)(this["ClearLogFileWhenExit"]));
            }
            set {
                this["ClearLogFileWhenExit"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PT. Allabare Berkatindo")]
        public string CompanyName {
            get {
                return ((string)(this["CompanyName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=anantha.atisicloud.com,8082;Initial Catalog=ALLABARE;User ID=sa;Passw" +
            "ord=p455w0rd.")]
        public string cnsetting {
            get {
                return ((string)(this["cnsetting"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseNetworkPrinter {
            get {
                return ((bool)(this["UseNetworkPrinter"]));
            }
            set {
                this["UseNetworkPrinter"] = value;
            }
        }
    }
}
